### DISCUSSION TITLE
GitHub Actions + Anvil.js setup

### DISCUSSION THREAD

**Discussion by v1rtl** [wagmi-dev/anvil.js#39] [Q&A]
Hi, I'm writing a viem library for Safe (multisig) and I want to run tests but I'm hitting an error like this:

```
Error: Anvil instance doesn't exist
```

my GitHub action for installing Anvil and running tests is like this:

```yaml
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: build packages
        run: pnpm build
      - name: run tests
        run: pnpm test:coverage
        env:
          VITE_ANVIL_FORK_URL: ${{ vars.VITE_ANVIL_FORK_URL }}
          VITE_ANVIL_BLOCK_NUMBER: ${{ vars.VITE_ANVIL_BLOCK_NUMBER }}
          VITE_ANVIL_SAFE_ADDRESS: ${{ vars.VITE_SAFE_ADDRESS }}

        # run coverage only on ubuntu
      - name: Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/lcov.info
```

The vars values are:

```env
VITE_ANVIL_FORK_URL=https://rpc.ankr.com/eth_goerli
VITE_ANVIL_BLOCK_NUMBER=10001349
```

I have copied the test setup from Anvil.js, but for some reason it doesn't detect Anvil :(

Here's the links:
 - failed job: https://github.com/StauroXYZ/piggybank/actions/runs/6784482727/job/18440865191
 - actions file: https://github.com/StauroXYZ/piggybank/blob/master/.github/workflows/ci.yml
